<?php

// This file is automatically generated, please do not edit it.
// To update configuration, use bin/setup plugins:* commands.

use Alchemy\Phrasea\Application;

return call_user_func(function (Application $app) {
    $paths = [];

    return $paths;
}, $app);
