version: "3.4"

services:
  elasticsearch:
    ports:
      - 9200:9200
    volumes:
      - ${PHRASEANET_ELASTICSEARCH_DIR}:/usr/share/elasticsearch/data:rw
    networks:
      - internal

  kibana:
    image: kibana:4.6.6
    ports:
      - 5601:5601
    links:
      - elasticsearch
    depends_on:
      - elasticsearch
    networks:
      - internal

  logstash:
    image: logstash:7.6.2
    links:
      - elasticsearch
    volumes:
      - ${PHRASEANET_CONFIG_DIR}:/var/alchemy/Phraseanet/config:rw
    command: logstash -f /var/alchemy/Phraseanet/config/logstash.conf
    depends_on:
      - elasticsearch
    restart: on-failure
    networks:
      - internal

  filebeat:
    hostname: filebeat
    image: "docker.elastic.co/beats/filebeat:7.6.2"
    volumes:
      - ${PHRASEANET_CONFIG_DIR}/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - ${PHRASEANET_LOGS_DIR}:/var/alchemy/Phraseanet/logs:ro
    command: filebeat run -e --strict.perms=false
    restart: on-failure
    networks:
      - internal
