<?php

require_once dirname(__FILE__) . '/../../PhraseanetPHPUnitAbstract.class.inc';

/**
 * Test class for Session_Authentication_Guest.
 * Generated by PHPUnit on 2011-08-02 at 15:48:08.
 */
class Session_Authentication_GuestTest extends PhraseanetPHPUnitAbstract
{

  /**
   * @var Session_Authentication_Guest
   */
  protected $object;

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  public function setUp()
  {
    $this->object = new Session_Authentication_Guest(appbox::get_instance());
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  public function tearDown()
  {

  }

  /**
   * @todo Implement testSignOn().
   */
  public function testSignOn()
  {
    $user = $this->object->signOn();
    $this->assertInstanceOf('User_Adapter', $user);
    $this->assertTrue($user->is_guest());
  }


}

?>
