<?php

namespace Repositories;

use Doctrine\ORM\EntityRepository;

/**
 * CategoryElementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryElementRepository extends EntityRepository
{
}
