<?php

namespace Repositories;

use Doctrine\ORM\EntityRepository;

/**
 * FeedEntryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FeedEntryRepository extends EntityRepository
{
}
