<?php

namespace Repositories;

use Doctrine\ORM\EntityRepository;

/**
 * OrderElementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderElementRepository extends EntityRepository
{
    public function find($id)
    {
        $dql = 'SELECT f FROM Entities\FeedPublisher f
                WHERE f.id = :id ';
        
        $query = $this->_em->createQuery($dql);
        $query->setParameter('id', $id);
        $feed = $query->getResult();
        
        return $feed[0];
    }
}
