<?php

/*
 * This file is part of Phraseanet
 *
 * (c) 2005-2013 Alchemy
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Repositories;

use Doctrine\ORM\EntityRepository;
use Entities\Feed;
use Entities\FeedPublisher;

/**
 * OrderElementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderElementRepository extends EntityRepository
{
    /**
     * Finds a FeedPublisher based on a given Feed and a User_Adapter.
     *
     * @param Feed          $feed
     * @param \User_Adapter $user
     *
     * @return FeedPublisher
     */
    public function findByUser(Feed $feed, \User_Adapter $user)
    {
        $dql = 'SELECT f FROM Entities\FeedPublisher f
                WHERE f.usr_id = :usrId AND f.feed = :feed';

        $query = $this->_em->createQuery($dql);
        $query->setParameter('usrId', $user->get_id());
        $query->setParameter('feed', $feed);

        return $query->getOneOrNullResult();
    }
}
