<?php

namespace Repositories;

use Doctrine\ORM\EntityRepository;

/**
 * StoryWZRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StoryWZRepository extends EntityRepository
{
  
  public function findByUser(\User_Adapter $user)
  {
    return $this->findBy(array('usr_id'=>$user->get_id()));
  }
  
}