<?php

namespace Repositories;

use Doctrine\ORM\EntityRepository;

/**
 * UsrAuthProvider
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsrAuthProvider extends EntityRepository
{
}
