<?php

namespace Repositories;

use Doctrine\ORM\EntityRepository;

/**
 * UsrListEntryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsrListEntryRepository extends EntityRepository
{
  
  /**
   * Get all lists entries matching a given User
   *
   * @param \User_Adapter $user
   * @param type $like 
   */
  public function findUserList(\User_Adapter $user)
  {
    $dql = 'SELECT l FROM Entities\UsrListEntry l 
              JOIN l.owners o
            WHERE o.usr_id = :usr_id';
    
    
    $params = array(
        'usr_id' => $user->get_id(),
    );

    $query = $this->_em->createQuery($dql);
    $query->setParameters($params);

    return $query->getResult();
  }
}