<?php

namespace Repositories;

use Doctrine\ORM\EntityRepository;

/**
 * BasketElementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BasketElementRepository extends EntityRepository
{
}
