{{- if and .Values.app.hpa.exportemail.enabled .Values.app.worker.launch.exportemail }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: worker-exportemail
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: phraseanet-worker-exportemail
  minReplicas: {{ .Values.app.hpa.exportemail.minReplicas }}
  maxReplicas: {{ .Values.app.hpa.exportemail.maxReplicas }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.app.hpa.exportemail.averageUtilization }}
{{- end }}