{{ if .Values.image.pullSecret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.image.pullSecret.name }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
{{- end }}