{{- if eq .Values.saml.enabled true }}
apiVersion: v1
kind: Service
metadata:
  name: phraseanet-saml-sp
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: phraseanet
    tier: saml-sp
{{- end }}