<?php

namespace Alchemy\Phrasea\Helper\Record;

require_once __DIR__ . '/../../../../PhraseanetPHPUnitAuthenticatedAbstract.class.inc';

/**
 * Test class for Push.
 * Generated by PHPUnit on 2012-01-12 at 12:16:06.
 */
class PrinterTest extends \PhraseanetPHPUnitAuthenticatedAbstract
{

  /**
   * @var Printer
   */
  protected $object;

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  public function setUp()
  {
    parent::setUp();
  }

  /**
   * @covers {className}::{origMethodName}
   * @todo Implement testGet_count_preview().
   */
  public function testGet_count_preview()
  {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
            'This test has not been implemented yet.'
    );
  }

  /**
   * @covers {className}::{origMethodName}
   * @todo Implement testGet_count_thumbnail().
   */
  public function testGet_count_thumbnail()
  {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
            'This test has not been implemented yet.'
    );
  }

}
