<?php
/*
 * This file is part of Phraseanet
 *
 * (c) 2005-2015 Alchemy
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */
namespace Alchemy\Phrasea\Plugin;

use Alchemy\Phrasea\Core\Configuration\PropertyAccess;
use Silex\Application;

class PluginManager
{
    /** @var PropertyAccess */
    private $config;
    /** @var PluginRepository */
    private $repository;
    /** @var \Twig_Environment */
    private $twig;
    /** @var string Path to plugin files */
    private $filename;

    /**
     * @param PluginRepository $repository
     * @param PropertyAccess   $config
     * @param string           $filename
     */
    public function __construct(PluginRepository $repository, PropertyAccess $config, $filename)
    {
        $this->repository = $repository;
        $this->config = $config;
        $this->filename = $filename;
    }

    /**
     * @param string $name
     * @return bool Whether configuration was changed
     * @throws PluginException
     */
    public function enablePlugin($name)
    {
        if ($this->isPluginEnabled($name)) {
            return false;
        }

        $name = strtolower($name);
        $this->repository->find($name);
        $this->config->set(['plugins', $name, 'enabled'], true);
        $this->dump();

        return true;
    }

    /**
     * @param string $name
     * @return bool Whether configuration was changed
     */
    public function disablePlugin($name)
    {
        if (!$this->isPluginEnabled($name)) {
            return false;
        }

        $this->config->set(['plugins', strtolower($name), 'enabled'], false);
        $this->dump();

        return true;
    }

    /**
     * @param string $name
     * @return bool Whether configuration was changed
     */
    public function removePlugin($name)
    {
        $name = strtolower($name);
        if (!$this->config->has(['plugins', $name])) {
            return false;
        }

        $this->config->remove(['plugins', $name, 'enabled']);
        $this->dump();

        return true;
    }

    /**
     * @param string $name
     * @return null|array
     */
    public function getPluginParameters($name)
    {
        return $this->config->get(['plugins', strtolower($name), 'parameters'], []);
    }

    /**
     * @param string $name
     * @param array  $parameters
     * @return bool Whether configuration was changed
     */
    public function setPluginParameters($name, array $parameters)
    {
        $this->config->set(['plugins', strtolower($name), 'parameters'], $parameters);
        $this->dump();

        return true;
    }

    /**
     * @param string $name
     * @return bool Whether configuration changed
     */
    public function unsetPluginParameters($name)
    {
        if (! $this->config->has(['plugins', strtolower($name), 'parameters'])) {
            return false;
        };

        $this->config->remove(['plugins', strtolower($name), 'parameters']);
        $this->dump();

        return true;
    }

    /**
     * @param string $name
     * @return bool
     */
    public function isPluginEnabled($name)
    {
        return $this->config->get(['plugins', strtolower($name), 'enabled'], false);
    }

    /**
     * @param \Twig_Environment $twig
     */
    public function setTwig(\Twig_Environment $twig)
    {
        $this->twig = $twig;
    }

    /**
     * @return \Twig_Environment
     */
    public function getTwig()
    {
        if (!$this->twig) {
            $templates = [
                'plugins.php' => '<?php
// This file is automatically generated, please do not edit it.

{% if plugins is empty %}
return [];
{% else %}
$plugins = array ();

{% for name, plugin in plugins %}
// plugin {{ name }}
{% if plugin.parameters is empty %}
$plugins[] = new {{ plugin.class }}(array ());
{% else %}
$parameters = {{ plugin.parameters|export }};
$plugins[] = new {{ plugin.class }}($parameters);
{% endif %}

{% endfor %}
return $plugins;
{% endif %}
',
            ];
            $loader = new \Twig_Loader_Array($templates);
            $this->twig = new \Twig_Environment($loader, ['autoescape' => false]);
            $this->twig->addFilter(new \Twig_SimpleFilter('export', function ($data) {
                return var_export($data, true);
            }));
        }

        return $this->twig;
    }

    public function dump()
    {
        $plugins = [];
        foreach ($this->repository->findAll() as $name => $class) {
            if ($this->isPluginEnabled($name)) {
                $plugins[$name] = ['class' => $class, 'parameters' => $this->getPluginParameters($name)];
            }
        }
        $loader = $this->getTwig()->render('plugins.php', ['plugins' => $plugins]);
        file_put_contents($this->filename, $loader);
    }
}
