<?php

// This file is automatically generated, please do not edit it.
// To update configuration, use bin/console plugins:* commands.

return call_user_func(function () {
    require __DIR__ . '/web-gallery/vendor/autoload.php';
    require __DIR__ . '/unibail-authentication/vendor/autoload.php';
    $loader = require __DIR__ . '/../vendor/autoload.php';

    return $loader;
});
