<?php

require_once __DIR__ . '/../../../../PhraseanetWebTestCaseAuthenticatedAbstract.class.inc';

/**
 * Test class for Subdefs.
 * Generated by PHPUnit on 2012-01-11 at 18:25:04.
 */
class DescriptionTest extends \PhraseanetWebTestCaseAuthenticatedAbstract
{

  /**
   * As controllers use WebTestCase, it requires a client
   */
  protected $client;

  /**
   * If the controller tests require some records, specify it her
   *
   * For example, this will loacd 2 records
   * (self::$record_1 and self::$record_2) :
   *
   * $need_records = 2;
   *
   */
  protected static $need_records = false;

  /**
   * The application loader
   */
  public function createApplication()
  {
    return require __DIR__ . '/../../../../../Alchemy/Phrasea/Application/Admin.php';
  }

  public function setUp()
  {
    parent::setUp();
    $this->client = $this->createClient();
  }

  /**
   * Default route test
   */
  public function testRouteSlash()
  {
    $this->markTestIncomplete();
    
    $appbox = appbox::get_instance();
    $databox = array_shift($appbox->get_databoxes());
    $fields = $databox->get_meta_structure();
    
    $fieldIds = array();
    
    foreach($fields as $field)
    {
      $fieldIds[] = $field->get_id();
    }
    
    $this->client->request("POST", "/description/" . $databox->get_sbas_id());
  }

}
