<?php

namespace Alchemy\Phrasea\Model\Proxies\__CG__\Alchemy\Phrasea\Model\Entities;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class FtpCredential extends \Alchemy\Phrasea\Model\Entities\FtpCredential implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Alchemy\\Phrasea\\Model\\Entities\\FtpCredential' . "\0" . 'id', '' . "\0" . 'Alchemy\\Phrasea\\Model\\Entities\\FtpCredential' . "\0" . 'user', '' . "\0" . 'Alchemy\\Phrasea\\Model\\Entities\\FtpCredential' . "\0" . 'active', '' . "\0" . 'Alchemy\\Phrasea\\Model\\Entities\\FtpCredential' . "\0" . 'address', '' . "\0" . 'Alchemy\\Phrasea\\Model\\Entities\\FtpCredential' . "\0" . 'login', '' . "\0" . 'Alchemy\\Phrasea\\Model\\Entities\\FtpCredential' . "\0" . 'password', '' . "\0" . 'Alchemy\\Phrasea\\Model\\Entities\\FtpCredential' . "\0" . 'receptionFolder', '' . "\0" . 'Alchemy\\Phrasea\\Model\\Entities\\FtpCredential' . "\0" . 'repositoryPrefixName', '' . "\0" . 'Alchemy\\Phrasea\\Model\\Entities\\FtpCredential' . "\0" . 'passive', '' . "\0" . 'Alchemy\\Phrasea\\Model\\Entities\\FtpCredential' . "\0" . 'ssl', '' . "\0" . 'Alchemy\\Phrasea\\Model\\Entities\\FtpCredential' . "\0" . 'maxRetry', '' . "\0" . 'Alchemy\\Phrasea\\Model\\Entities\\FtpCredential' . "\0" . 'updated'];
        }

        return ['__isInitialized__', '' . "\0" . 'Alchemy\\Phrasea\\Model\\Entities\\FtpCredential' . "\0" . 'id', '' . "\0" . 'Alchemy\\Phrasea\\Model\\Entities\\FtpCredential' . "\0" . 'user', '' . "\0" . 'Alchemy\\Phrasea\\Model\\Entities\\FtpCredential' . "\0" . 'active', '' . "\0" . 'Alchemy\\Phrasea\\Model\\Entities\\FtpCredential' . "\0" . 'address', '' . "\0" . 'Alchemy\\Phrasea\\Model\\Entities\\FtpCredential' . "\0" . 'login', '' . "\0" . 'Alchemy\\Phrasea\\Model\\Entities\\FtpCredential' . "\0" . 'password', '' . "\0" . 'Alchemy\\Phrasea\\Model\\Entities\\FtpCredential' . "\0" . 'receptionFolder', '' . "\0" . 'Alchemy\\Phrasea\\Model\\Entities\\FtpCredential' . "\0" . 'repositoryPrefixName', '' . "\0" . 'Alchemy\\Phrasea\\Model\\Entities\\FtpCredential' . "\0" . 'passive', '' . "\0" . 'Alchemy\\Phrasea\\Model\\Entities\\FtpCredential' . "\0" . 'ssl', '' . "\0" . 'Alchemy\\Phrasea\\Model\\Entities\\FtpCredential' . "\0" . 'maxRetry', '' . "\0" . 'Alchemy\\Phrasea\\Model\\Entities\\FtpCredential' . "\0" . 'updated'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (FtpCredential $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getUser()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUser', []);

        return parent::getUser();
    }

    /**
     * {@inheritDoc}
     */
    public function setUser(\Alchemy\Phrasea\Model\Entities\User $user)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUser', [$user]);

        return parent::setUser($user);
    }

    /**
     * {@inheritDoc}
     */
    public function isActive()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isActive', []);

        return parent::isActive();
    }

    /**
     * {@inheritDoc}
     */
    public function setActive($active)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setActive', [$active]);

        return parent::setActive($active);
    }

    /**
     * {@inheritDoc}
     */
    public function getAddress()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAddress', []);

        return parent::getAddress();
    }

    /**
     * {@inheritDoc}
     */
    public function setAddress($address)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAddress', [$address]);

        return parent::setAddress($address);
    }

    /**
     * {@inheritDoc}
     */
    public function getLogin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLogin', []);

        return parent::getLogin();
    }

    /**
     * {@inheritDoc}
     */
    public function setLogin($login)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLogin', [$login]);

        return parent::setLogin($login);
    }

    /**
     * {@inheritDoc}
     */
    public function getPassword()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPassword', []);

        return parent::getPassword();
    }

    /**
     * {@inheritDoc}
     */
    public function setPassword($password)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPassword', [$password]);

        return parent::setPassword($password);
    }

    /**
     * {@inheritDoc}
     */
    public function getReceptionFolder()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReceptionFolder', []);

        return parent::getReceptionFolder();
    }

    /**
     * {@inheritDoc}
     */
    public function setReceptionFolder($receptionFolder)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setReceptionFolder', [$receptionFolder]);

        return parent::setReceptionFolder($receptionFolder);
    }

    /**
     * {@inheritDoc}
     */
    public function getRepositoryPrefixName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRepositoryPrefixName', []);

        return parent::getRepositoryPrefixName();
    }

    /**
     * {@inheritDoc}
     */
    public function setRepositoryPrefixName($repositoryPrefixName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRepositoryPrefixName', [$repositoryPrefixName]);

        return parent::setRepositoryPrefixName($repositoryPrefixName);
    }

    /**
     * {@inheritDoc}
     */
    public function isPassive()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isPassive', []);

        return parent::isPassive();
    }

    /**
     * {@inheritDoc}
     */
    public function setPassive($passive)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPassive', [$passive]);

        return parent::setPassive($passive);
    }

    /**
     * {@inheritDoc}
     */
    public function isSsl()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isSsl', []);

        return parent::isSsl();
    }

    /**
     * {@inheritDoc}
     */
    public function setSsl($ssl)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSsl', [$ssl]);

        return parent::setSsl($ssl);
    }

    /**
     * {@inheritDoc}
     */
    public function getMaxRetry()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMaxRetry', []);

        return parent::getMaxRetry();
    }

    /**
     * {@inheritDoc}
     */
    public function setMaxRetry($maxRetry)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMaxRetry', [$maxRetry]);

        return parent::setMaxRetry($maxRetry);
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdated()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdated', []);

        return parent::getUpdated();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdated(\DateTime $updated)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdated', [$updated]);

        return parent::setUpdated($updated);
    }

}
