{{- if .Values.expose.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: expose-client
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
  selector:
    app: phraseanet-services
    tier: expose-client
{{- end }}
