binaries:
    php_binary: ''
    convert_binary: ''
    composite_binary: ''
    swf_extract_binary: ''
    pdf2swf_binary: ''
    swf_render_binary: ''
    unoconv_binary: ''
    ffmpeg_binary: ''
    ffprobe_binary: ''
    mp4box_binary: ''
    pdftotext_binary: ''
