{{- range .Values._internal.services }}
{{- $appName := . }}
{{- if (index $.Values $appName).enabled }}
{{- with (index $.Values $appName)  }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $appName }}-api-php
spec:
  ports:
  - name: http
    port: 9000
    targetPort: 9000
  selector:
    app: phraseanet-services
    tier: {{ $appName }}-api-php
---
{{- end }}
{{- end }}
{{- end }}
