<?php

namespace Alchemy\Phrasea\Model\Proxies\__CG__\Alchemy\Phrasea\Model\Entities;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Task extends \Alchemy\Phrasea\Model\Entities\Task implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Alchemy\\Phrasea\\Model\\Entities\\Task' . "\0" . 'id', '' . "\0" . 'Alchemy\\Phrasea\\Model\\Entities\\Task' . "\0" . 'name', '' . "\0" . 'Alchemy\\Phrasea\\Model\\Entities\\Task' . "\0" . 'jobId', '' . "\0" . 'Alchemy\\Phrasea\\Model\\Entities\\Task' . "\0" . 'settings', '' . "\0" . 'Alchemy\\Phrasea\\Model\\Entities\\Task' . "\0" . 'completed', '' . "\0" . 'Alchemy\\Phrasea\\Model\\Entities\\Task' . "\0" . 'status', '' . "\0" . 'Alchemy\\Phrasea\\Model\\Entities\\Task' . "\0" . 'crashed', '' . "\0" . 'Alchemy\\Phrasea\\Model\\Entities\\Task' . "\0" . 'singleRun', '' . "\0" . 'Alchemy\\Phrasea\\Model\\Entities\\Task' . "\0" . 'created', '' . "\0" . 'Alchemy\\Phrasea\\Model\\Entities\\Task' . "\0" . 'updated', '' . "\0" . 'Alchemy\\Phrasea\\Model\\Entities\\Task' . "\0" . 'lastExecution', '' . "\0" . 'Alchemy\\Phrasea\\Model\\Entities\\Task' . "\0" . 'period');
        }

        return array('__isInitialized__', '' . "\0" . 'Alchemy\\Phrasea\\Model\\Entities\\Task' . "\0" . 'id', '' . "\0" . 'Alchemy\\Phrasea\\Model\\Entities\\Task' . "\0" . 'name', '' . "\0" . 'Alchemy\\Phrasea\\Model\\Entities\\Task' . "\0" . 'jobId', '' . "\0" . 'Alchemy\\Phrasea\\Model\\Entities\\Task' . "\0" . 'settings', '' . "\0" . 'Alchemy\\Phrasea\\Model\\Entities\\Task' . "\0" . 'completed', '' . "\0" . 'Alchemy\\Phrasea\\Model\\Entities\\Task' . "\0" . 'status', '' . "\0" . 'Alchemy\\Phrasea\\Model\\Entities\\Task' . "\0" . 'crashed', '' . "\0" . 'Alchemy\\Phrasea\\Model\\Entities\\Task' . "\0" . 'singleRun', '' . "\0" . 'Alchemy\\Phrasea\\Model\\Entities\\Task' . "\0" . 'created', '' . "\0" . 'Alchemy\\Phrasea\\Model\\Entities\\Task' . "\0" . 'updated', '' . "\0" . 'Alchemy\\Phrasea\\Model\\Entities\\Task' . "\0" . 'lastExecution', '' . "\0" . 'Alchemy\\Phrasea\\Model\\Entities\\Task' . "\0" . 'period');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Task $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setName($name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', array($name));

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', array());

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setJobId($jobId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setJobId', array($jobId));

        return parent::setJobId($jobId);
    }

    /**
     * {@inheritDoc}
     */
    public function getJobId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getJobId', array());

        return parent::getJobId();
    }

    /**
     * {@inheritDoc}
     */
    public function setSettings($settings)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSettings', array($settings));

        return parent::setSettings($settings);
    }

    /**
     * {@inheritDoc}
     */
    public function getSettings()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSettings', array());

        return parent::getSettings();
    }

    /**
     * {@inheritDoc}
     */
    public function setCompleted($completed)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCompleted', array($completed));

        return parent::setCompleted($completed);
    }

    /**
     * {@inheritDoc}
     */
    public function isCompleted()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isCompleted', array());

        return parent::isCompleted();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatus($status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatus', array($status));

        return parent::setStatus($status);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatus', array());

        return parent::getStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setCrashed($crashed)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCrashed', array($crashed));

        return parent::setCrashed($crashed);
    }

    /**
     * {@inheritDoc}
     */
    public function getCrashed()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCrashed', array());

        return parent::getCrashed();
    }

    /**
     * {@inheritDoc}
     */
    public function setSingleRun($singleRun)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSingleRun', array($singleRun));

        return parent::setSingleRun($singleRun);
    }

    /**
     * {@inheritDoc}
     */
    public function isSingleRun()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isSingleRun', array());

        return parent::isSingleRun();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreated($created)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreated', array($created));

        return parent::setCreated($created);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreated()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreated', array());

        return parent::getCreated();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdated($updated)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdated', array($updated));

        return parent::setUpdated($updated);
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdated()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdated', array());

        return parent::getUpdated();
    }

    /**
     * {@inheritDoc}
     */
    public function setExecuted($lastExecution)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setExecuted', array($lastExecution));

        return parent::setExecuted($lastExecution);
    }

    /**
     * {@inheritDoc}
     */
    public function getLastExecution()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLastExecution', array());

        return parent::getLastExecution();
    }

    /**
     * {@inheritDoc}
     */
    public function getPeriod()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPeriod', array());

        return parent::getPeriod();
    }

    /**
     * {@inheritDoc}
     */
    public function setPeriod($period)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPeriod', array($period));

        return parent::setPeriod($period);
    }

}
