<?php

require_once dirname(__FILE__) . '/PhraseanetPHPUnitAuthenticatedAbstract.class.inc';

/**
 * Test class for lazaret.
 * Generated by PHPUnit on 2011-05-31 at 12:37:19.
 */
class lazaretTest extends PhraseanetPHPUnitAuthenticatedAbstract
{

  /**
   * @var lazaret
   */
  protected $object;

  public function setUp()
  {
    parent::setUp();
    $this->object = new lazaret;
  }

  public function testIsOk()
  {
    $this->markTestIncomplete();
    foreach ($this->object->get_elements() as $element)
    {

    }
  }

}

