<?php

require_once dirname(__FILE__) . '/PhraseanetPHPUnitAbstract.class.inc';

/**
 * Test class for logs.
 * Generated by PHPUnit on 2011-07-06 at 18:40:27.
 */
class logsTest extends PhraseanetPHPUnitAbstract
{

  /**
   * @var logs
   */
  protected $object;

  /**
   * @todo Implement testRotate().
   */
  public function testRotate()
  {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
            'This test has not been implemented yet.'
    );
  }

}

?>
