<?php

require_once dirname(__FILE__) . '/PhraseanetPHPUnitAbstract.class.inc';

/**
 * Test class for setup.
 * Generated by PHPUnit on 2011-07-06 at 18:33:21.
 */
class setupTest extends PhraseanetPHPUnitAbstract
{

  /**
   * @todo Implement testCreate_global_values().
   */
  public function testCreate_global_values()
  {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
            'This test has not been implemented yet.'
    );
  }

  /**
   * @todo Implement testCheck_binaries().
   */
  public function testCheck_binaries()
  {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
            'This test has not been implemented yet.'
    );
  }

  /**
   * @todo Implement testCheck_mod_auth_token().
   */
  public function testCheck_mod_auth_token()
  {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
            'This test has not been implemented yet.'
    );
  }

  /**
   * @todo Implement testCheck_apache().
   */
  public function testCheck_apache()
  {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
            'This test has not been implemented yet.'
    );
  }

  /**
   * @todo Implement testCheck_phrasea().
   */
  public function testCheck_phrasea()
  {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
            'This test has not been implemented yet.'
    );
  }

  /**
   * @todo Implement testCheck_writability().
   */
  public function testCheck_writability()
  {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
            'This test has not been implemented yet.'
    );
  }

  /**
   * @todo Implement testCheck_mail_form().
   */
  public function testCheck_mail_form()
  {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
            'This test has not been implemented yet.'
    );
  }

  /**
   * @todo Implement testCheck_php_version().
   */
  public function testCheck_php_version()
  {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
            'This test has not been implemented yet.'
    );
  }

  /**
   * @todo Implement testCheck_php_extension().
   */
  public function testCheck_php_extension()
  {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
            'This test has not been implemented yet.'
    );
  }

  /**

  /**
   * @todo Implement testCheck_cache_memcache().
   */
  public function testCheck_cache_memcache()
  {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
            'This test has not been implemented yet.'
    );
  }

  /**
   * @todo Implement testCheck_cache_opcode().
   */
  public function testCheck_cache_opcode()
  {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
            'This test has not been implemented yet.'
    );
  }

  /**
   * @todo Implement testCheck_php_configuration().
   */
  public function testCheck_php_configuration()
  {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
            'This test has not been implemented yet.'
    );
  }

  /**
   * @todo Implement testCheck_sphinx_search().
   */
  public function testCheck_sphinx_search()
  {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
            'This test has not been implemented yet.'
    );
  }

  /**
   * @todo Implement testCheck_system_locales().
   */
  public function testCheck_system_locales()
  {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
            'This test has not been implemented yet.'
    );
  }

  /**
   * @todo Implement testCreateAdmin().
   */
  public function testCreateAdmin()
  {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
            'This test has not been implemented yet.'
    );
  }

  /**
   * @todo Implement testWrite_config().
   */
  public function testWrite_config()
  {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
            'This test has not been implemented yet.'
    );
  }

  /**
   * @todo Implement testCreateBase().
   */
  public function testCreateBase()
  {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
            'This test has not been implemented yet.'
    );
  }

}

?>
