<?php

require_once __DIR__ . '/PhraseanetPHPUnitAbstract.class.inc';

/**
 * Test class for thesaurus.
 * Generated by PHPUnit on 2011-07-06 at 18:30:03.
 */
class thesaurusTest extends PhraseanetPHPUnitAbstract
{

  public function testXquery_escape()
  {
    $string = 'Eléphant ';
    $this->assertEquals($string, thesaurus::xquery_escape($string));
    $string = '&é"\'(-è_ çà)=ù*!:;,?./§%µ+°0987654321';
    $this->assertEquals('&amp;é&quot;&apos;(-è_ çà)=ù*!:;,?./§%µ+°0987654321', thesaurus::xquery_escape($string));
  }

}

