<?php
require_once dirname(__FILE__) . '/PhraseanetPHPUnitAbstract.class.inc';

/**
 * Test class for random.
 * Generated by PHPUnit on 2011-05-27 at 18:41:53.
 */
class unitTestsTest extends PhraseanetPHPUnitAbstract
{

  public function testFiles()
  {
    $testDir = dirname(__FILE__).'/';
    foreach (new RecursiveIteratorIterator(new RecursiveDirectoryIterator($testDir), RecursiveIteratorIterator::LEAVES_ONLY) as $file)
    {
      if (strpos($file, '/.svn/') !== false)
        continue;
      if (substr($file->getFilename(), 0, 1) === '.')
        continue;
      if (substr($file->getFilename(), -4) !== '.php')
        continue;


      $this->assertRegExp('/[a-zA-Z0-9-_\.]+Test.php/', $file->getFilename(), 'Verify that all tests files names');
    }
  }

}

