<?php

require_once __DIR__ . '/../../PhraseanetPHPUnitAbstract.class.inc';

/**
 * Test class for databox_subdef_audio.
 * Generated by PHPUnit on 2011-11-03 at 15:21:34.
 */
class databox_subdef_audioTest extends PhraseanetPHPUnitAbstract
{

  /**
   * @var databox_subdef_audio
   */
  protected $object;

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  public function setUp()
  {

  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  public function tearDown()
  {

  }

  public function testToImplement()
  {
    $this->markTestIncomplete();
  }

}

?>
