<?php

namespace Alchemy\Phrasea\Model\Repositories;

use Alchemy\Phrasea\Model\Entities\PsSettings;
use Doctrine\ORM\EntityRepository;

/**
 * PsSettingKeysRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PsSettingKeysRepository extends EntityRepository
{
    public function get(string $name=null, PsSettings $parent=null, array $values = [], int $maxResult=null)
    {
        $crit = [];
        if(!is_null($name)) {
            $crit['name'] = $name;
        }
        if(!is_null($parent)) {
            $crit['parent'] = $parent;
        }
        foreach($values as $k => $v) {
            $crit[$k] = $v;
        }

        return $this->findBy($crit, null, $maxResult);
    }

    public function delete(string $key=null, PsSettings $setting=null, array $values = [])
    {
        foreach ($this->get($key, $setting, $values) as $e) {
            $this->getEntityManager()->remove($e);
        }
    }

    public function getEntityManager()
    {
        return $this->_em;
    }

}
