<?php

/*
 * This file is part of Phraseanet
 *
 * (c) 2005-2014 Alchemy
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Alchemy\Phrasea\Model\Repositories;

use Alchemy\Phrasea\Model\Entities\Task;
use Doctrine\ORM\EntityRepository;

/**
 * TaskRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaskRepository extends EntityRepository
{
    public function findActiveTasks()
    {
        $qb = $this->createQueryBuilder('t');
        $qb->where('t.status = :status');

        $qb->setParameter(':status', Task::STATUS_STARTED);

        return $qb->getQuery()->getResult();
    }
}
