<?php

require_once dirname(__FILE__) . '/../../../PhraseanetPHPUnitAbstract.class.inc';

/**
 * Test class for databox_subdef_mediatype_audio.
 * Generated by PHPUnit on 2011-11-03 at 15:21:41.
 */
class databox_subdef_mediatype_audioTest extends PhraseanetPHPUnitAbstract
{

  /**
   * @var databox_subdef_mediatype_audio
   */
  protected $object;

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  public function setUp()
  {

  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  public function tearDown()
  {

  }

  /**
   * @todo Implement testGet_available_options().
   */
  public function testGet_available_options()
  {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
            'This test has not been implemented yet.'
    );
  }

}

?>
