<?php

namespace Proxies\__CG__\Alchemy\Phrasea\Model\Entities;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class FtpExportElement extends \Alchemy\Phrasea\Model\Entities\FtpExportElement implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setRecordId($recordId)
    {
        $this->__load();
        return parent::setRecordId($recordId);
    }

    public function getRecordId()
    {
        $this->__load();
        return parent::getRecordId();
    }

    public function setBaseId($baseId)
    {
        $this->__load();
        return parent::setBaseId($baseId);
    }

    public function getBaseId()
    {
        $this->__load();
        return parent::getBaseId();
    }

    public function setSubdef($subdef)
    {
        $this->__load();
        return parent::setSubdef($subdef);
    }

    public function getSubdef()
    {
        $this->__load();
        return parent::getSubdef();
    }

    public function setFilename($filename)
    {
        $this->__load();
        return parent::setFilename($filename);
    }

    public function getFilename()
    {
        $this->__load();
        return parent::getFilename();
    }

    public function setFolder($folder)
    {
        $this->__load();
        return parent::setFolder($folder);
    }

    public function getFolder()
    {
        $this->__load();
        return parent::getFolder();
    }

    public function setError($error)
    {
        $this->__load();
        return parent::setError($error);
    }

    public function isError()
    {
        $this->__load();
        return parent::isError();
    }

    public function setDone($done)
    {
        $this->__load();
        return parent::setDone($done);
    }

    public function isDone()
    {
        $this->__load();
        return parent::isDone();
    }

    public function setBusinessfields($businessfields)
    {
        $this->__load();
        return parent::setBusinessfields($businessfields);
    }

    public function isBusinessfields()
    {
        $this->__load();
        return parent::isBusinessfields();
    }

    public function setCreated(\DateTime $created)
    {
        $this->__load();
        return parent::setCreated($created);
    }

    public function getCreated()
    {
        $this->__load();
        return parent::getCreated();
    }

    public function setUpdated(\DateTime $updated)
    {
        $this->__load();
        return parent::setUpdated($updated);
    }

    public function getUpdated()
    {
        $this->__load();
        return parent::getUpdated();
    }

    public function setExport(\Alchemy\Phrasea\Model\Entities\FtpExport $export = NULL)
    {
        $this->__load();
        return parent::setExport($export);
    }

    public function getExport()
    {
        $this->__load();
        return parent::getExport();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'recordId', 'baseId', 'subdef', 'filename', 'folder', 'error', 'done', 'businessfields', 'created', 'updated', 'export');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}