<?php

namespace Proxies;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class EntitiesValidationDataProxy extends \Entities\ValidationData implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }


    public function getId()
    {
        $this->__load();

        return parent::getId();
    }

    public function setAgreement($agreement)
    {
        $this->__load();

        return parent::setAgreement($agreement);
    }

    public function getAgreement()
    {
        $this->__load();

        return parent::getAgreement();
    }

    public function setNote($note)
    {
        $this->__load();

        return parent::setNote($note);
    }

    public function getNote()
    {
        $this->__load();

        return parent::getNote();
    }

    public function setUpdated($updated)
    {
        $this->__load();

        return parent::setUpdated($updated);
    }

    public function getUpdated()
    {
        $this->__load();

        return parent::getUpdated();
    }

    public function setParticipant(\Entities\ValidationParticipant $participant)
    {
        $this->__load();

        return parent::setParticipant($participant);
    }

    public function getParticipant()
    {
        $this->__load();

        return parent::getParticipant();
    }

    public function setBasketElement(\Entities\BasketElement $basketElement)
    {
        $this->__load();

        return parent::setBasketElement($basketElement);
    }

    public function getBasketElement()
    {
        $this->__load();

        return parent::getBasketElement();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'agreement', 'note', 'updated', 'participant', 'basket_element');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }

    }
}
