<?php

require_once __DIR__ . '/../../PhraseanetPHPUnitAbstract.class.inc';

/**
 * Test class for databox_subdef_document.
 * Generated by PHPUnit on 2011-11-03 at 15:21:33.
 */
class databox_subdef_documentTest extends PhraseanetPHPUnitAbstract
{

  /**
   * @var databox_subdef_document
   */
  protected $object;

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  public function setUp()
  {

  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  public function tearDown()
  {

  }

  public function testToImplement()
  {
    $this->markTestIncomplete();
  }
}

?>
