#! /bin/bash

# open rabbitmq ports
sudo iptables -I INPUT -p tcp --dport 15672 -j ACCEPT

# open elastic search ports
sudo iptables -I INPUT -p tcp --dport 9200 -j ACCEPT

# open mysql ports
sudo iptables -I INPUT -p tcp --dport 3306 -j ACCEPT

# locales

export LANGUAGE=fr_FR.UTF-8
export LANG=fr_FR.UTF-8
export LC_ALL=fr_FR.UTF-8

source ~/.bashrc