name: Build and push image and image-layer cache

on:
  workflow_call:
    inputs:
      image:
        required: true
        type: string
      image_registry:
        required: true
        type: string
      cache_registry:
        required: true
        type: string
      context:
        required: true
        type: string
      file:
        required: true
        type: string
      target:
        required: true
        type: string

env:
  PHRASEANET_DOCKER_TAG: ${{ github.head_ref }}

jobs:
  buid:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Log into registry ${{ inputs.image_registry }}
        uses: docker/login-action@v2
        with:
          registry: ${{ inputs.image_registry }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      - name: build ${{ inputs.image }}
        uses: docker/build-push-action@v4
        with:
          context: ${{ inputs.context }}
          file: ${{ inputs.file }}
          push: true
          cache-from: type=registry,ref=${{ inputs.cache_registry }}/${{ inputs.image }}:build-cache
          cache-to: type=registry,mode=max,ref=${{ inputs.cache_registry }}/${{ inputs.image }}:build-cache
          target: ${{ inputs.target }}
          tags: ${{ inputs.image_registry }}/${{ inputs.image }}:${{ env.PHRASEANET_DOCKER_TAG }}
