name: testCI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build-test:

    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: build all image and install
        run: |
          docker compose build
          docker compose up -d
      - name: init tools test
        run: |
          docker compose exec -T phraseanet curl -sS https://getcomposer.org/installer -o /tmp/composer-setup.php
          docker compose exec -T phraseanet php /tmp/composer-setup.php --install-dir=/usr/local/bin --filename=composer
          docker compose exec -T phraseanet composer install --ignore-platform-reqs --no-interaction
          docker compose exec -T -e PHRASEANET_BASE_URL=http://127.0.0.1 phraseanet docker/phraseanet/setup/auto-install.sh
          docker compose exec -T phraseanet bin/developer ini:setup-tests-dbs -v
          docker compose exec -T phraseanet bin/developer phraseanet:regenerate-sqlite -v
          docker compose exec -T phraseanet bin/developer phraseanet:generate-js-fixtures -v
          docker compose exec -T phraseanet bin/console system:clear-cache
      - name: test
        run: |
          docker compose exec -T phraseanet php -d memory_limit=-1 vendor/phpunit/phpunit/phpunit  --exclude-group legacy
          docker compose exec -T phraseanet php -d memory_limit=-1 vendor/phpunit/phpunit/phpunit  --group legacy --exclude-group web
          docker compose exec -T phraseanet php -d memory_limit=-1 vendor/phpunit/phpunit/phpunit --group web
