name: testCI

on: [push]

jobs:

  build-test:

    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3
        # test to pull directly
      - name: build all image and install
        run: |
          docker-compose pull
          docker-compose up -d
      - name: init test
        run: |
          docker-compose exec phraseanet bin/developer ini:setup-tests-dbs -v
          docker-compose exec phraseanet bin/console searchengine:index:create -v
          docker-compose exec phraseanet bin/developer phraseanet:regenerate-sqlite -v
          docker-compose exec phraseanet bin/developer phraseanet:generate-js-fixtures -v
      - name: test
        run: |
          docker-compose exec phraseanet bin/phpunit  --exclude-group legacy
          docker-compose exec phraseanet bin/phpunit  --group legacy --exclude-group web
          docker-compose exec phraseanet bin/phpunit --group web
