name: testCI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  PHRASEANET_DOCKER_TAG: ${{ github.head_ref }}
  REGISTRY: ghcr.io/${{ github.repository_owner }}
jobs:

  build-test:

    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      - name: build phraseanet-setup
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: false
          load: true
          cache-from: type=gha,scope=phraseanet-setup
          cache-to: type=gha,mode=max,scope=phraseanet-setup
          target: phraseanet-setup
          tags: ${{ env.REGISTRY }}/phraseanet-setup:${{ env.PHRASEANET_DOCKER_TAG }}
      - name: build phraseanet-nginx
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: false
          load: true
          cache-from: type=gha,scope=phraseanet-nginx
          cache-to: type=gha,mode=max,scope=phraseanet-nginx
          target: phraseanet-nginx
          tags: ${{ env.REGISTRY }}/phraseanet-nginx:${{ env.PHRASEANET_DOCKER_TAG }}
      - name: build phraseanet-fpm
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: false
          load: true
          cache-from: type=gha,scope=phraseanet-fpm
          cache-to: type=gha,mode=max,scope=phraseanet-fpm
          target: phraseanet-fpm
          tags: ${{ env.REGISTRY }}/phraseanet-fpm:${{ env.PHRASEANET_DOCKER_TAG }}
      - name: build phraseanet-worker
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: false
          load: true
          cache-from: type=gha,scope=phraseanet-worker
          cache-to: type=gha,mode=max,scope=phraseanet-worker
          target: phraseanet-worker
          tags: ${{ env.REGISTRY }}/phraseanet-worker:${{ env.PHRASEANET_DOCKER_TAG }}
      - name: build phraseanet-db
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/db/Dockerfile
          push: false
          load: true
          cache-from: type=gha,scope=phraseanet-db
          cache-to: type=gha,mode=max,scope=phraseanet-db
          tags: ${{ env.REGISTRY }}/phraseanet-db:${{ env.PHRASEANET_DOCKER_TAG }}
      - name: build phraseanet-elasticsearch
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/elasticsearch/Dockerfile
          push: false
          load: true
          cache-from: type=gha,scope=phraseanet-elasticsearch
          cache-to: type=gha,mode=max,scope=phraseanet-elasticsearch
          tags: ${{ env.REGISTRY }}/phraseanet-elasticsearch:${{ env.PHRASEANET_DOCKER_TAG }}
      - name: install
        run: |
          PHRASEANET_DOCKER_TAG=${{ env.PHRASEANET_DOCKER_TAG }} docker compose pull
          PHRASEANET_DOCKER_TAG=${{ env.PHRASEANET_DOCKER_TAG }} docker compose up -d
      - name: init tools test
        run: |
          docker compose exec -T phraseanet curl -sS https://getcomposer.org/installer -o /tmp/composer-setup.php
          docker compose exec -T phraseanet php /tmp/composer-setup.php --install-dir=/usr/local/bin --filename=composer
          docker compose exec -T phraseanet composer install --ignore-platform-reqs --no-interaction
          docker compose exec -T -e PHRASEANET_BASE_URL=http://127.0.0.1 phraseanet docker/phraseanet/setup/auto-install.sh
          docker compose exec -T phraseanet bin/developer ini:setup-tests-dbs -v
          docker compose exec -T phraseanet bin/developer phraseanet:regenerate-sqlite -v
          docker compose exec -T phraseanet bin/developer phraseanet:generate-js-fixtures -v
      - name: test
        run: |
          docker compose exec -T phraseanet bin/console system:clear-cache
          docker compose exec -T phraseanet php -d memory_limit=-1 vendor/phpunit/phpunit/phpunit  --exclude-group legacy
          docker compose exec -T phraseanet bin/console system:clear-cache
          docker compose exec -T phraseanet php -d memory_limit=-1 vendor/phpunit/phpunit/phpunit  --group legacy --exclude-group web
          docker compose exec -T phraseanet bin/console system:clear-cache
          docker compose exec -T phraseanet php -d memory_limit=-1 vendor/phpunit/phpunit/phpunit --group web
