
image:
  registry: alchemyfr
  tag:
      phraseanet: 4.1.3
      database: 4.1.3
      elasticsearch: 4.1.3

mysql:
  enabled: true
  user: "{{ .Values.app.phraseanet_db_user }}"
  password: "{{ .Values.app.phraseanet_db_password }}"
  root_password: "{{ .Values.app.phraseanet_db_password }}"
  max_allowed_packet: 16M
  pvc_name: phraseanet-database
  resources:
    requests:
      cpu: "50m"
      memory: "256Mi"
    limits:
      cpu: "2000m"
      memory: "4096Mi"
  persistence:
    enabled: true
    existingClaim:
    storageClass:
    annotations: {}
    accessMode: ReadWriteOnce
    subPath:
    size: 1Gi

elasticsearch:
  enabled: true
  pvc_name: phraseanet-elasticsearch
  resources:
    requests:
      cpu: "50m"
      memory: "256Mi"
    limits:
      cpu: "2000m"
      memory: "4096Mi"
  persistence:
    enabled: true
    existingClaim:
    storageClass:
    annotations: {}
    accessMode: ReadWriteOnce
    subPath:
    size: 1Gi

rabbitmq:
  enabled: true
  port: "{{ .Values.app.phraseanet_rabbitmq_port }}"
  default_user: "{{ .Values.app.phraseanet_rabbitmq_user }}"
  default_pass: "{{ .Values.app.phraseanet_rabbitmq_pass }}"
  default_vhost: "{{ .Values.app.phraseanet_rabbitmq_vhost }}"
  heartbeat: 60
  resources:
    requests:
      cpu: "50m"
      memory: "256Mi"
    limits:
      cpu: "2000m"
      memory: "4096Mi"

redis:
  enabled: true
  port: "{{ .Values.app.phraseanet_cache_port }}"

http:
  max_body_size: 2G
  max_input_vars: 12000

php:
  opcache_enabled: 1
  log_level: warning
  session_cache_limiter: off
  session_save_handler: redis
  session_save_path: "tcp://redis-session:6379"

ingress:
  enabled: false
  host: phraseanet
  tls: false

app:
  phraseanet_hostname: localhost
  phraseanet_scheme: http
  phraseanet_install: 1
  phraseanet_setup: 1
  phraseanet_admin_account_email: admin@alchemy.fr
  phraseanet_admin_account_password: phraseanet
  phraseanet_db_host: db
  phraseanet_db_user: root
  phraseanet_db_password: phraseanet
  phraseanet_cache_type: redis
  phraseanet_cache_host: redis
  phraseanet_cache_port: 6379
  phraseanet_cache_domain: phraseanet
  phraseanet_elasticsearch_host: elasticsearch
  phraseanet_elasticsearch_port: 9200
  phraseanet_rabbitmq_host: rabbitmq
  phraseanet_rabbitmq_port: 5672
  phraseanet_rabbitmq_ssl: false
  phraseanet_rabbitmq_vhost: /
  phraseanet_rabbitmq_user: rabbit
  phraseanet_rabbitmq_pass: rabbit
  phraseanet_install: 1
  phraseanet_setup: 1
  phraseanet_upgrade: 1
  phraseanet_smtp_enabled:
  phraseanet_smtp_auth_enabled:
  phraseanet_smtp_secure_mode:
  phraseanet_smtp_host:
  phraseanet_smtp_port:
  phraseanet_smtp_user:
  phraseanet_smtp_password:
  phraseanet_emitter_email:
  phraseanet_mail_object_prefix:
  phraseanet_ffmpeg_timeout:
  phraseanet_ffprobe_timeout:
  phraseanet_gs_timeout:
  phraseanet_mp4box_timeout:
  phraseanet_swftools_timeout:
  phraseanet_unocon_timeout:
  phraseanet_exiftool_timeout:
  install_db_template: DublinCore
  install_appbox: ab_master
  install_databox: db_databox1
  phraseanet_trusted_proxies:
  gateway:
    resources:
      requests:
        cpu: "50m"
        memory: "32Mi"
      limits:
        cpu: "2000m"
        memory: "4096Mi"
  web:
    resources:
      requests:
        cpu: "50m"
        memory: "256Mi"
      limits:
        cpu: "2000m"
        memory: "4096Mi"
  worker:
    resources:
      requests:
        cpu: "50m"
        memory: "256Mi"
      limits:
        cpu: "2000m"
        memory: "4096Mi"
  pvc:
    data:
      name: phraseanet-datas
      persistence:
        enabled: true
        existingClaim:
        storageClass:
        annotations: {}
        accessMode: ReadWriteOnce
        subPath:
        size: 1Gi
    thumbnails:
      name: phraseanet-thumbnails
      persistence:
        enabled: true
        existingClaim:
        storageClass:
        annotations: {}
        accessMode: ReadWriteOnce
        subPath:
        size: 1Gi
    custom:
      name: phraseanet-custom
      persistence:
        enabled: true
        existingClaim:
        storageClass:
        annotations: {}
        accessMode: ReadWriteOnce
        subPath:
        size: 1Gi
    config:
      name: phraseanet-config
      persistence:
        enabled: true
        existingClaim:
        storageClass:
        annotations: {}
        accessMode: ReadWriteOnce
        subPath:
        size: 1Gi
    wwwplugins:
      name: phraseanet-wwwplugins
      persistence:
        enabled: true
        existingClaim:
        storageClass:
        annotations: {}
        accessMode: ReadWriteOnce
        subPath:
        size: 1Gi
    tmp:
      name: phraseanet-tmp
      persistence:
        enabled: true
        existingClaim:
        storageClass:
        annotations: {}
        accessMode: ReadWriteOnce
        subPath:
        size: 1Gi
  persistence:
    enabled: true
    existingClaim:
    storageClass:
    annotations: {}
    accessMode: ReadWriteOnce
    subPath:
    size: 1Gi
  pvc_name:
      data: phraseanet-datas
      thumbnails: phraseanet-thumbnails
      custom: phraseanet-custom
      config: phraseanet-config
